-- Nodd v1 baseline schema.
-- Forward-only: do not edit this file after release; ship a new 0002_*.sql instead.

-- ============================================================
-- Tables
-- ============================================================

create table projects (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now()
);
alter table projects enable row level security;

create type project_role as enum ('member', 'admin');

create table project_members (
  project_id  uuid not null references projects(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  role        project_role not null default 'member',
  created_at  timestamptz not null default now(),
  primary key (project_id, user_id)
);
alter table project_members enable row level security;

create table threads (
  id           uuid primary key default gen_random_uuid(),
  project_id   uuid not null references projects(id) on delete cascade,
  url_path     text not null,
  pin          jsonb not null,
  state_key    text not null default '',
  resolved     boolean not null default false,
  resolved_by  uuid references auth.users(id),
  resolved_at  timestamptz,
  created_by   uuid not null references auth.users(id),
  created_at   timestamptz not null default now()
);
alter table threads enable row level security;

-- Pin shape guard: the client always writes {selector, offsetX, offsetY, ...}.
-- Reject malformed pins written directly via the Data API so the overlay's
-- anchoring resolver never receives a non-string selector or non-numeric offset.
alter table threads add constraint threads_pin_shape check (
  jsonb_typeof(pin) = 'object'
  and jsonb_typeof(pin -> 'selector') = 'string'
  and jsonb_typeof(pin -> 'offsetX') = 'number'
  and jsonb_typeof(pin -> 'offsetY') = 'number'
);

create table comments (
  id          uuid primary key default gen_random_uuid(),
  thread_id   uuid not null references threads(id) on delete cascade,
  author_id   uuid not null references auth.users(id),
  body        text not null,
  mentions    uuid[] not null default '{}',
  created_at  timestamptz not null default now(),
  edited_at   timestamptz
);
alter table comments enable row level security;

-- ============================================================
-- View + helper (RLS policies depend on these)
-- ============================================================

create or replace view profiles as
select
  u.id,
  u.email,
  coalesce(u.raw_user_meta_data ->> 'display_name', split_part(u.email, '@', 1)) as display_name,
  u.raw_user_meta_data ->> 'avatar_url' as avatar_url
from auth.users u
where u.id in (
  select pm.user_id
  from project_members pm
  where pm.project_id in (
    select pm2.project_id
    from project_members pm2
    where pm2.user_id = auth.uid()
  )
);

grant select on profiles to authenticated;

create or replace function is_project_member(_project_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from project_members
    where project_id = _project_id
      and user_id    = auth.uid()
  );
$$;

revoke all on function is_project_member(uuid) from public;
grant execute on function is_project_member(uuid) to authenticated;

-- ============================================================
-- RLS policies
-- ============================================================

create policy projects_select_member on projects
  for select using (is_project_member(id));

create policy members_select_member on project_members
  for select using (is_project_member(project_id));

create policy threads_select_member on threads
  for select using (is_project_member(project_id));

create policy threads_insert_member on threads
  for insert with check (
    is_project_member(project_id) and created_by = auth.uid()
  );

create policy threads_update_resolve on threads
  for update using (is_project_member(project_id))
  with check    (is_project_member(project_id));

create policy threads_delete_author on threads
  for delete using (is_project_member(project_id) and created_by = auth.uid());

create policy comments_select_member on comments
  for select using (
    exists (
      select 1 from threads t
      where t.id = comments.thread_id
        and is_project_member(t.project_id)
    )
  );

create policy comments_insert_member on comments
  for insert with check (
    author_id = auth.uid()
    and exists (
      select 1 from threads t
      where t.id = comments.thread_id
        and is_project_member(t.project_id)
    )
  );

create policy comments_update_author on comments
  for update using (author_id = auth.uid())
  with check    (author_id = auth.uid());

create policy comments_delete_author on comments
  for delete using (author_id = auth.uid());

-- ============================================================
-- Indexes
-- ============================================================

create index threads_project_path_idx
  on threads (project_id, url_path)
  where resolved = false;

create index comments_thread_idx
  on comments (thread_id, created_at);

-- ============================================================
-- Realtime publication
-- ============================================================

alter publication supabase_realtime add table threads;
alter publication supabase_realtime add table comments;

-- ============================================================
-- Data API grants (required for Supabase projects from 2026-05-30)
-- ============================================================
-- anon excluded: all RLS policies require project membership.

grant select, insert, update, delete
  on public.projects
  to authenticated, service_role;

grant select, insert, update, delete
  on public.project_members
  to authenticated, service_role;

grant select, insert, update, delete
  on public.threads
  to authenticated, service_role;

grant select, insert, update, delete
  on public.comments
  to authenticated, service_role;
